version: '3.3'

services:
  db: 
    image: postgres:13.0
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "5432:5432"
    
  flask:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app

volumes:
  db_data:
